import { GetServerSideProps } from 'next';
import Head from 'next/head';
import { Navbar, Hero, Modal, Row, SubscriptionPlan } from 'src/components';
import { IMovie, Product } from 'src/interfaces/app.interface';
import { API_REQUEST } from '../services/api.services';
import { useInfoStore } from 'src/store';

export default function Home({
	trending,
	topRated,
	tvTopRated,
	popular,
	documentary,
	family,
	history,
	comedy,
	products,
	subscription,
}: HomeProps): JSX.Element {
	const { modal } = useInfoStore();


	if (!subscription.length) return <SubscriptionPlan products={products} />;

	return (
		<div
			className={`relative min-h-screen bg-gradient-to-b from-gray-900/20 to-[#010511] ${modal && '!h-screen overflow-hidden'}`}
		>
			<Head>
				<title>Home - Sammi</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/logo.svg' />
			</Head>
			<Navbar />


			<main className='relative pl-4 pb-16 lg:pb-24 lg:space-y-24 lg:pl-16'>

				<Hero trending={trending} />
				<section>
					<Row title='Top Rated' movies={topRated} isBig={true}/>
					<Row title='Tv Show' movies={tvTopRated}  />
					<Row title='Documentary' movies={documentary} />
					<Row title='History' movies={history} />
					<Row title='Family' movies={family} />
					<Row title='Popular' movies={popular} />
					<Row title='Comedy' movies={comedy} />
				</section>
			</main>
			{modal && <Modal />}
		</div>
	);
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async ({ req }) => {
	const user_id = req.cookies.user_id;

	if (!user_id) {
		return {
			redirect: { destination: '/auth', permanent: false },
		};
	}

	const [trending, topRated, tvTopRated, popular, documentary, comedy, family, history, products, subscription] =
		await Promise.all([
			fetch(API_REQUEST.trending).then(res => res.json()),
			fetch(API_REQUEST.top_rated).then(res => res.json()),
			fetch(API_REQUEST.tv_top_rated).then(res => res.json()),
			fetch(API_REQUEST.movie_popular).then(res => res.json()),
			fetch(API_REQUEST.documnetary).then(res => res.json()),
			fetch(API_REQUEST.comedy).then(res => res.json()),
			fetch(API_REQUEST.family).then(res => res.json()),
			fetch(API_REQUEST.history).then(res => res.json()),
			fetch(API_REQUEST.products_list).then(res => res.json()),
			fetch(`${API_REQUEST.subscription}/${user_id}`).then(res => res.json()),
		]);


	return {
		props: {
			trending: trending.results,
			topRated: topRated.results,
			tvTopRated: tvTopRated.results,
			popular: popular.results,
			documentary: documentary.results,
			comedy: comedy.results,
			family: family.results,
			history: history.results,
			products: products.products.data,
			subscription: subscription.subscription.data,
		},
	};
};

interface HomeProps {
	trending: IMovie[];
	topRated: IMovie[];
	tvTopRated: IMovie[];
	popular: IMovie[];
	documentary: IMovie[];
	comedy: IMovie[];
	family: IMovie[];
	history: IMovie[];
	products: Product[];
	subscription: string[];
}